{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sqlalchemy as sqla\n",
    "from sqlalchemy import create_engine\n",
    "import traceback\n",
    "import glob\n",
    "import os\n",
    "from pprint import pprint\n",
    "import simplejson as json\n",
    "import requests\n",
    "import time\n",
    "from IPython.display import display"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    "URI = \"dbikes.cmd8vuwgew1e.us-east-1.rds.amazonaws.com\"\n",
    "PORT = \"3306\"\n",
    "DB = \"dbikes\"\n",
    "USER = \"admin\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "engine = create_engine(\"mysql+mysqldb://{}:{}@{}:{}/{}\".format(USER, PASSWORD, URI, PORT, DB), echo=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (3351531065.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;36m  Input \u001b[1;32mIn [52]\u001b[1;36m\u001b[0m\n\u001b[1;33m    INFO sqlalchemy.engine.base.Engine\u001b[0m\n\u001b[1;37m         ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "sql = engine.execute(sql)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationalError",
     "evalue": "(MySQLdb._exceptions.OperationalError) (1049, \"Unknown database 'database-1'\")\n(Background on this error at: https://sqlalche.me/e/14/e3q8)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3243\u001b[0m, in \u001b[0;36mEngine._wrap_pool_connect\u001b[1;34m(self, fn, connection)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3241'>3242</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m-> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3242'>3243</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m fn()\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3243'>3244</a>\u001b[0m \u001b[39mexcept\u001b[39;00m dialect\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mError \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:310\u001b[0m, in \u001b[0;36mPool.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=302'>303</a>\u001b[0m \u001b[39m\"\"\"Return a DBAPI connection from the pool.\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=303'>304</a>\u001b[0m \n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=304'>305</a>\u001b[0m \u001b[39mThe connection is instrumented such that when its\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=307'>308</a>\u001b[0m \n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=308'>309</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=309'>310</a>\u001b[0m \u001b[39mreturn\u001b[39;00m _ConnectionFairy\u001b[39m.\u001b[39;49m_checkout(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:868\u001b[0m, in \u001b[0;36m_ConnectionFairy._checkout\u001b[1;34m(cls, pool, threadconns, fairy)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=866'>867</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m fairy:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=867'>868</a>\u001b[0m     fairy \u001b[39m=\u001b[39m _ConnectionRecord\u001b[39m.\u001b[39;49mcheckout(pool)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=869'>870</a>\u001b[0m     fairy\u001b[39m.\u001b[39m_pool \u001b[39m=\u001b[39m pool\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:476\u001b[0m, in \u001b[0;36m_ConnectionRecord.checkout\u001b[1;34m(cls, pool)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=473'>474</a>\u001b[0m \u001b[39m@classmethod\u001b[39m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=474'>475</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mcheckout\u001b[39m(\u001b[39mcls\u001b[39m, pool):\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=475'>476</a>\u001b[0m     rec \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_do_get()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=476'>477</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:146\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=144'>145</a>\u001b[0m         \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=145'>146</a>\u001b[0m             \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_dec_overflow()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=146'>147</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:143\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=141'>142</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=142'>143</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_create_connection()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=143'>144</a>\u001b[0m \u001b[39mexcept\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:256\u001b[0m, in \u001b[0;36mPool._create_connection\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=253'>254</a>\u001b[0m \u001b[39m\"\"\"Called by subclasses to create a new ConnectionRecord.\"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=255'>256</a>\u001b[0m \u001b[39mreturn\u001b[39;00m _ConnectionRecord(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:371\u001b[0m, in \u001b[0;36m_ConnectionRecord.__init__\u001b[1;34m(self, pool, connect)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=369'>370</a>\u001b[0m \u001b[39mif\u001b[39;00m connect:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=370'>371</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__connect()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=371'>372</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfinalize_callback \u001b[39m=\u001b[39m deque()\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:666\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=664'>665</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=665'>666</a>\u001b[0m         pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mError on connect(): \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, e)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=666'>667</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=667'>668</a>\u001b[0m     \u001b[39m# in SQLAlchemy 1.4 the first_connect event is not used by\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=668'>669</a>\u001b[0m     \u001b[39m# the engine, so this will usually not be set\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:661\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=659'>660</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstarttime \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=660'>661</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi_connection \u001b[39m=\u001b[39m connection \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_invoke_creator(\u001b[39mself\u001b[39;49m)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=661'>662</a>\u001b[0m pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mCreated new connection \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m\"\u001b[39m, connection)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\create.py:590\u001b[0m, in \u001b[0;36mcreate_engine.<locals>.connect\u001b[1;34m(connection_record)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/create.py?line=588'>589</a>\u001b[0m             \u001b[39mreturn\u001b[39;00m connection\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/create.py?line=589'>590</a>\u001b[0m \u001b[39mreturn\u001b[39;00m dialect\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\default.py:584\u001b[0m, in \u001b[0;36mDefaultDialect.connect\u001b[1;34m(self, *cargs, **cparams)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/default.py?line=581'>582</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m, \u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams):\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/default.py?line=582'>583</a>\u001b[0m     \u001b[39m# inherits the docstring from interfaces.Dialect.connect\u001b[39;00m\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/default.py?line=583'>584</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\MySQLdb\\__init__.py:123\u001b[0m, in \u001b[0;36mConnect\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/__init__.py?line=120'>121</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mMySQLdb\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mconnections\u001b[39;00m \u001b[39mimport\u001b[39;00m Connection\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/__init__.py?line=122'>123</a>\u001b[0m \u001b[39mreturn\u001b[39;00m Connection(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\MySQLdb\\connections.py:185\u001b[0m, in \u001b[0;36mConnection.__init__\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=182'>183</a>\u001b[0m autocommit \u001b[39m=\u001b[39m kwargs2\u001b[39m.\u001b[39mpop(\u001b[39m\"\u001b[39m\u001b[39mautocommit\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mFalse\u001b[39;00m)\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=184'>185</a>\u001b[0m \u001b[39msuper\u001b[39m()\u001b[39m.\u001b[39m\u001b[39m__init__\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs2)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=185'>186</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcursorclass \u001b[39m=\u001b[39m cursorclass\n",
      "\u001b[1;31mOperationalError\u001b[0m: (1049, \"Unknown database 'database-1'\")",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\michael\\Desktop\\Dublin_bikes_project\\bikes1.ipynb Cell 5'\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/michael/Desktop/Dublin_bikes_project/bikes1.ipynb#ch0000006?line=0'>1</a>\u001b[0m \u001b[39mfor\u001b[39;00m res \u001b[39min\u001b[39;00m engine\u001b[39m.\u001b[39;49mexecute(\u001b[39m\"\u001b[39;49m\u001b[39mSHow Variables;\u001b[39;49m\u001b[39m\"\u001b[39;49m):\n\u001b[0;32m      <a href='vscode-notebook-cell:/c%3A/Users/michael/Desktop/Dublin_bikes_project/bikes1.ipynb#ch0000006?line=1'>2</a>\u001b[0m     \u001b[39mprint\u001b[39m(res)\n",
      "File \u001b[1;32m<string>:2\u001b[0m, in \u001b[0;36mexecute\u001b[1;34m(self, statement, *multiparams, **params)\u001b[0m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py:401\u001b[0m, in \u001b[0;36m_decorate_with_warning.<locals>.warned\u001b[1;34m(fn, *args, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/deprecations.py?line=398'>399</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m skip_warning:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/deprecations.py?line=399'>400</a>\u001b[0m     _warn_with_version(message, version, wtype, stacklevel\u001b[39m=\u001b[39m\u001b[39m3\u001b[39m)\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/deprecations.py?line=400'>401</a>\u001b[0m \u001b[39mreturn\u001b[39;00m fn(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3138\u001b[0m, in \u001b[0;36mEngine.execute\u001b[1;34m(self, statement, *multiparams, **params)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3111'>3112</a>\u001b[0m \u001b[39m@util\u001b[39m\u001b[39m.\u001b[39mdeprecated_20(\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3112'>3113</a>\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39m:meth:`_engine.Engine.execute`\u001b[39m\u001b[39m\"\u001b[39m,\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3113'>3114</a>\u001b[0m     alternative\u001b[39m=\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mAll statement execution in SQLAlchemy 2.0 is performed \u001b[39m\u001b[39m\"\u001b[39m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3118'>3119</a>\u001b[0m )\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3119'>3120</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mexecute\u001b[39m(\u001b[39mself\u001b[39m, statement, \u001b[39m*\u001b[39mmultiparams, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mparams):\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3120'>3121</a>\u001b[0m     \u001b[39m\"\"\"Executes the given construct and returns a\u001b[39;00m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3121'>3122</a>\u001b[0m \u001b[39m    :class:`_engine.CursorResult`.\u001b[39;00m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3122'>3123</a>\u001b[0m \n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3135'>3136</a>\u001b[0m \n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3136'>3137</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3137'>3138</a>\u001b[0m     connection \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnect(close_with_result\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m)\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3138'>3139</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m connection\u001b[39m.\u001b[39mexecute(statement, \u001b[39m*\u001b[39mmultiparams, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mparams)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3197\u001b[0m, in \u001b[0;36mEngine.connect\u001b[1;34m(self, close_with_result)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3181'>3182</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m, close_with_result\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m):\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3182'>3183</a>\u001b[0m     \u001b[39m\"\"\"Return a new :class:`_engine.Connection` object.\u001b[39;00m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3183'>3184</a>\u001b[0m \n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3184'>3185</a>\u001b[0m \u001b[39m    The :class:`_engine.Connection` object is a facade that uses a DBAPI\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3193'>3194</a>\u001b[0m \n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3194'>3195</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3196'>3197</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_connection_cls(\u001b[39mself\u001b[39;49m, close_with_result\u001b[39m=\u001b[39;49mclose_with_result)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:96\u001b[0m, in \u001b[0;36mConnection.__init__\u001b[1;34m(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events, _allow_revalidate)\u001b[0m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=90'>91</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39m=\u001b[39m _branch_from\u001b[39m.\u001b[39m_has_events\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=91'>92</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=92'>93</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_dbapi_connection \u001b[39m=\u001b[39m (\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=93'>94</a>\u001b[0m         connection\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=94'>95</a>\u001b[0m         \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m---> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=95'>96</a>\u001b[0m         \u001b[39melse\u001b[39;00m engine\u001b[39m.\u001b[39;49mraw_connection()\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=96'>97</a>\u001b[0m     )\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=98'>99</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_transaction \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_nested_transaction \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=99'>100</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__savepoint_seq \u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3276\u001b[0m, in \u001b[0;36mEngine.raw_connection\u001b[1;34m(self, _connection)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3253'>3254</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mraw_connection\u001b[39m(\u001b[39mself\u001b[39m, _connection\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3254'>3255</a>\u001b[0m     \u001b[39m\"\"\"Return a \"raw\" DBAPI connection from the connection pool.\u001b[39;00m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3255'>3256</a>\u001b[0m \n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3256'>3257</a>\u001b[0m \u001b[39m    The returned object is a proxied version of the DBAPI\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3273'>3274</a>\u001b[0m \n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3274'>3275</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3275'>3276</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_wrap_pool_connect(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mpool\u001b[39m.\u001b[39;49mconnect, _connection)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3246\u001b[0m, in \u001b[0;36mEngine._wrap_pool_connect\u001b[1;34m(self, fn, connection)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3243'>3244</a>\u001b[0m \u001b[39mexcept\u001b[39;00m dialect\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3244'>3245</a>\u001b[0m     \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m-> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3245'>3246</a>\u001b[0m         Connection\u001b[39m.\u001b[39;49m_handle_dbapi_exception_noconnection(\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3246'>3247</a>\u001b[0m             e, dialect, \u001b[39mself\u001b[39;49m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3247'>3248</a>\u001b[0m         )\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3248'>3249</a>\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3249'>3250</a>\u001b[0m         util\u001b[39m.\u001b[39mraise_(\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3250'>3251</a>\u001b[0m             sys\u001b[39m.\u001b[39mexc_info()[\u001b[39m1\u001b[39m], with_traceback\u001b[39m=\u001b[39msys\u001b[39m.\u001b[39mexc_info()[\u001b[39m2\u001b[39m]\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3251'>3252</a>\u001b[0m         )\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:2100\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception_noconnection\u001b[1;34m(cls, e, dialect, engine)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=2097'>2098</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=2098'>2099</a>\u001b[0m \u001b[39melif\u001b[39;00m should_wrap:\n\u001b[1;32m-> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=2099'>2100</a>\u001b[0m     util\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=2100'>2101</a>\u001b[0m         sqlalchemy_exception, with_traceback\u001b[39m=\u001b[39;49mexc_info[\u001b[39m2\u001b[39;49m], from_\u001b[39m=\u001b[39;49me\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=2101'>2102</a>\u001b[0m     )\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=2102'>2103</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=2103'>2104</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(exc_info[\u001b[39m1\u001b[39m], with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m])\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=203'>204</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3243\u001b[0m, in \u001b[0;36mEngine._wrap_pool_connect\u001b[1;34m(self, fn, connection)\u001b[0m\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3240'>3241</a>\u001b[0m dialect \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3241'>3242</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m-> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3242'>3243</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m fn()\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3243'>3244</a>\u001b[0m \u001b[39mexcept\u001b[39;00m dialect\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m   <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/base.py?line=3244'>3245</a>\u001b[0m     \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:310\u001b[0m, in \u001b[0;36mPool.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=301'>302</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=302'>303</a>\u001b[0m     \u001b[39m\"\"\"Return a DBAPI connection from the pool.\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=303'>304</a>\u001b[0m \n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=304'>305</a>\u001b[0m \u001b[39m    The connection is instrumented such that when its\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=307'>308</a>\u001b[0m \n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=308'>309</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=309'>310</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m _ConnectionFairy\u001b[39m.\u001b[39;49m_checkout(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:868\u001b[0m, in \u001b[0;36m_ConnectionFairy._checkout\u001b[1;34m(cls, pool, threadconns, fairy)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=864'>865</a>\u001b[0m \u001b[39m@classmethod\u001b[39m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=865'>866</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_checkout\u001b[39m(\u001b[39mcls\u001b[39m, pool, threadconns\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, fairy\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=866'>867</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m fairy:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=867'>868</a>\u001b[0m         fairy \u001b[39m=\u001b[39m _ConnectionRecord\u001b[39m.\u001b[39;49mcheckout(pool)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=869'>870</a>\u001b[0m         fairy\u001b[39m.\u001b[39m_pool \u001b[39m=\u001b[39m pool\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=870'>871</a>\u001b[0m         fairy\u001b[39m.\u001b[39m_counter \u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:476\u001b[0m, in \u001b[0;36m_ConnectionRecord.checkout\u001b[1;34m(cls, pool)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=473'>474</a>\u001b[0m \u001b[39m@classmethod\u001b[39m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=474'>475</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mcheckout\u001b[39m(\u001b[39mcls\u001b[39m, pool):\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=475'>476</a>\u001b[0m     rec \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_do_get()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=476'>477</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=477'>478</a>\u001b[0m         dbapi_connection \u001b[39m=\u001b[39m rec\u001b[39m.\u001b[39mget_connection()\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:146\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=143'>144</a>\u001b[0m     \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=144'>145</a>\u001b[0m         \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=145'>146</a>\u001b[0m             \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_dec_overflow()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=146'>147</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=147'>148</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_do_get()\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=67'>68</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=74'>75</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m compat\u001b[39m.\u001b[39mpy3k \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m]:\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=75'>76</a>\u001b[0m         \u001b[39m# emulate Py3K's behavior of telling us when an exception\u001b[39;00m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=76'>77</a>\u001b[0m         \u001b[39m# occurs in an exception handler.\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=203'>204</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:143\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=140'>141</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_inc_overflow():\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=141'>142</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=142'>143</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_create_connection()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=143'>144</a>\u001b[0m     \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/impl.py?line=144'>145</a>\u001b[0m         \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:256\u001b[0m, in \u001b[0;36mPool._create_connection\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=252'>253</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_create_connection\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=253'>254</a>\u001b[0m     \u001b[39m\"\"\"Called by subclasses to create a new ConnectionRecord.\"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=255'>256</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m _ConnectionRecord(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:371\u001b[0m, in \u001b[0;36m_ConnectionRecord.__init__\u001b[1;34m(self, pool, connect)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=368'>369</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__pool \u001b[39m=\u001b[39m pool\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=369'>370</a>\u001b[0m \u001b[39mif\u001b[39;00m connect:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=370'>371</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__connect()\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=371'>372</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfinalize_callback \u001b[39m=\u001b[39m deque()\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:666\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=663'>664</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=664'>665</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=665'>666</a>\u001b[0m         pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mError on connect(): \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, e)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=666'>667</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=667'>668</a>\u001b[0m     \u001b[39m# in SQLAlchemy 1.4 the first_connect event is not used by\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=668'>669</a>\u001b[0m     \u001b[39m# the engine, so this will usually not be set\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=669'>670</a>\u001b[0m     \u001b[39mif\u001b[39;00m pool\u001b[39m.\u001b[39mdispatch\u001b[39m.\u001b[39mfirst_connect:\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=67'>68</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=74'>75</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m compat\u001b[39m.\u001b[39mpy3k \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m]:\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=75'>76</a>\u001b[0m         \u001b[39m# emulate Py3K's behavior of telling us when an exception\u001b[39;00m\n\u001b[0;32m     <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/langhelpers.py?line=76'>77</a>\u001b[0m         \u001b[39m# occurs in an exception handler.\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=203'>204</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\pool\\base.py:661\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=658'>659</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=659'>660</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstarttime \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=660'>661</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi_connection \u001b[39m=\u001b[39m connection \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_invoke_creator(\u001b[39mself\u001b[39;49m)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=661'>662</a>\u001b[0m     pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mCreated new connection \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m\"\u001b[39m, connection)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/pool/base.py?line=662'>663</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfresh \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\create.py:590\u001b[0m, in \u001b[0;36mcreate_engine.<locals>.connect\u001b[1;34m(connection_record)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/create.py?line=587'>588</a>\u001b[0m         \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/create.py?line=588'>589</a>\u001b[0m             \u001b[39mreturn\u001b[39;00m connection\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/create.py?line=589'>590</a>\u001b[0m \u001b[39mreturn\u001b[39;00m dialect\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\sqlalchemy\\engine\\default.py:584\u001b[0m, in \u001b[0;36mDefaultDialect.connect\u001b[1;34m(self, *cargs, **cparams)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/default.py?line=581'>582</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m, \u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams):\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/default.py?line=582'>583</a>\u001b[0m     \u001b[39m# inherits the docstring from interfaces.Dialect.connect\u001b[39;00m\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/sqlalchemy/engine/default.py?line=583'>584</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\MySQLdb\\__init__.py:123\u001b[0m, in \u001b[0;36mConnect\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/__init__.py?line=119'>120</a>\u001b[0m \u001b[39m\"\"\"Factory function for connections.Connection.\"\"\"\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/__init__.py?line=120'>121</a>\u001b[0m \u001b[39mfrom\u001b[39;00m \u001b[39mMySQLdb\u001b[39;00m\u001b[39m.\u001b[39;00m\u001b[39mconnections\u001b[39;00m \u001b[39mimport\u001b[39;00m Connection\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/__init__.py?line=122'>123</a>\u001b[0m \u001b[39mreturn\u001b[39;00m Connection(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\envs\\comp30830\\lib\\site-packages\\MySQLdb\\connections.py:185\u001b[0m, in \u001b[0;36mConnection.__init__\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=181'>182</a>\u001b[0m \u001b[39m# PEP-249 requires autocommit to be initially off\u001b[39;00m\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=182'>183</a>\u001b[0m autocommit \u001b[39m=\u001b[39m kwargs2\u001b[39m.\u001b[39mpop(\u001b[39m\"\u001b[39m\u001b[39mautocommit\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mFalse\u001b[39;00m)\n\u001b[1;32m--> <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=184'>185</a>\u001b[0m \u001b[39msuper\u001b[39m()\u001b[39m.\u001b[39m\u001b[39m__init__\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs2)\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=185'>186</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mcursorclass \u001b[39m=\u001b[39m cursorclass\n\u001b[0;32m    <a href='file:///~/anaconda3/envs/comp30830/lib/site-packages/MySQLdb/connections.py?line=186'>187</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mencoders \u001b[39m=\u001b[39m {k: v \u001b[39mfor\u001b[39;00m k, v \u001b[39min\u001b[39;00m conv\u001b[39m.\u001b[39mitems() \u001b[39mif\u001b[39;00m \u001b[39mtype\u001b[39m(k) \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mint\u001b[39m}\n",
      "\u001b[1;31mOperationalError\u001b[0m: (MySQLdb._exceptions.OperationalError) (1049, \"Unknown database 'database-1'\")\n(Background on this error at: https://sqlalche.me/e/14/e3q8)"
     ]
    }
   ],
   "source": [
    "for res in engine.execute(\"SHow Variables;\"):\n",
    "    print(res)"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "d5dea15d4d3dc6786458e22d62e4ba2bd341ff2ef4845fb99d6d9876cbc85d3e"
  },
  "kernelspec": {
   "display_name": "Python 3.9.7 ('comp30830')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
